<a href="https://colab.research.google.com/github/OssamaSijbesma/uu-data-analysis-and-machine-learning-assignment-1/blob/main/report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Assignment 1: Supervised learning competition](https://daml.robertab.nl/assignments/assignment_1.html)

In [24]:
# Install packages in notebook
%pip install pyreadr --quiet

In [25]:
import pyreadr
import requests
import io
import pandas as pd
import xgboost as xgb

GOOGLE_COLAB = True # When using Google Colab set to True.
DATA_SOURCE = "https://github.com/OssamaSijbesma/uu-data-analysis-and-machine-learning-assignment-1/raw/refs/heads/main/"

if(GOOGLE_COLAB):
  # Fetch files from online data source
  train_response = requests.get(DATA_SOURCE+"raw/train.rds")
  test_response = requests.get(DATA_SOURCE+"raw/test.rds")
  train_rds = pyreadr.read_r(io.BytesIO(train_response.content))
  test_rds = pyreadr.read_r(io.BytesIO(test_response.content))
else:
  # Fetch files from local data source
  train_rds = pyreadr.read_r("./raw/train.rds")
  test_rds = pyreadr.read_r("./raw/test.rds")

# Create pandas data frames from files
train_df = pd.DataFrame.from_dict(train_rds[None])
test_df = pd.DataFrame.from_dict(test_rds[None])

# Data description

Describe the data and use a visualization to support your story. (approx. one or two paragraphs)

In [12]:
train_df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,score
0,GP,F,18.0,U,GT3,T,3.0,2.0,other,services,...,yes,yes,5.0,4.0,3.0,2.0,3.0,1.0,7.0,0.648402
1,GP,F,17.0,U,GT3,T,3.0,4.0,services,other,...,yes,no,4.0,4.0,5.0,1.0,3.0,5.0,16.0,1.169019
2,GP,M,17.0,U,GT3,T,2.0,3.0,other,other,...,yes,no,5.0,2.0,2.0,1.0,1.0,2.0,4.0,0.384039
3,GP,M,18.0,R,GT3,T,4.0,3.0,teacher,services,...,yes,yes,5.0,3.0,2.0,1.0,2.0,4.0,9.0,1.207493
4,GP,F,16.0,U,GT3,T,1.0,3.0,at_home,services,...,yes,yes,4.0,3.0,5.0,1.0,1.0,3.0,0.0,-1.215206

Warning: Total number of columns (31) exceeds max_columns (20) limiting to first (20) columns.

In [8]:
train_df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,score
count,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000
mean,16.753165,2.737342,2.503165,1.452532,2.034810,0.370253,3.933544,3.218354,3.066456,1.468354,2.287975,3.465190,5.718354,-0.016197
std,1.302923,1.105828,1.102662,0.690728,0.840667,0.788167,0.904318,0.972533,1.097767,0.881347,1.278385,1.385431,8.303744,0.986209
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-2.705322
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,-0.634936
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,3.500000,4.000000,-0.027688
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,0.640293
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,2.234578

In [23]:
categorical_values = {
    col: train_df[col].unique().tolist()
    for col in train_df.select_dtypes(include=['object', 'category']).columns
}

for key in categorical_values:
  print(f"{key}: {categorical_values[key]}")

school: ['GP', 'MS']
sex: ['F', 'M']
address: ['U', 'R']
famsize: ['GT3', 'LE3']
Pstatus: ['T', 'A']
Mjob: ['other', 'services', 'teacher', 'at_home', 'health']
Fjob: ['services', 'other', 'at_home', 'teacher', 'health']
reason: ['other', 'course', 'home', 'reputation']
guardian: ['mother', 'father', 'other']
schoolsup: ['no', 'yes']
famsup: ['no', 'yes']
paid: ['no', 'yes']
activities: ['no', 'yes']
nursery: ['yes', 'no']
higher: ['yes', 'no']
internet: ['yes', 'no']
romantic: ['yes', 'no']

# Model description

Briefly describe which models you compare to perform prediction. (approx. two or three paragraphs)

K-NN
Random Forrest
XG-Boost
Log odds

# Data transformation and pre-processing

Describe additional pre-processing steps you have used, if any (e.g., dealing with categorical data, scaling). If you do not do any pre-processing, you can leave this section out.

# Model comparison

Describe how you compare the methods and why. (approx. two or three paragraphs)

# Chosen model

Show which method is best and why. (approx. one paragraph) You are welcome to use tables and plots!

# Team member contributions

Write down what each team member contributed to the project.

- Author One: a, b, c
- Author Two: b, c, d
- Author Three: a, b, d