<a href="https://colab.research.google.com/github/OssamaSijbesma/uu-data-analysis-and-machine-learning-assignment-1/blob/main/report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Assignment 1: Supervised learning competition](https://daml.robertab.nl/assignments/assignment_1.html)

In [ ]:
# Install packages in notebook
%pip install pyreadr optuna --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 788.4/788.4 kB 17.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.4/442.4 kB 30.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.7/268.7 kB 19.2 MB/s eta 0:00:00

In [ ]:
import pyreadr
import requests
import io
import optuna
import pandas as pd
import xgboost as xgb
import numpy as np
from sklearn.model_selection import KFold, cross_val_score, RandomizedSearchCV
from sklearn.feature_selection import RFECV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, root_mean_squared_error
from scipy.stats import randint, uniform, loguniform
import matplotlib.pyplot as plt

GOOGLE_COLAB = True # When using Google Colab set to True.
DATA_SOURCE = "https://github.com/OssamaSijbesma/uu-data-analysis-and-machine-learning-assignment-1/raw/refs/heads/main/"

if(GOOGLE_COLAB):
  # Fetch files from online data source
  train_response = requests.get(DATA_SOURCE+"raw/train.rds")
  test_response = requests.get(DATA_SOURCE+"raw/test.rds")
  train_rds = pyreadr.read_r(io.BytesIO(train_response.content))
  test_rds = pyreadr.read_r(io.BytesIO(test_response.content))
else:
  # Fetch files from local data source
  train_rds = pyreadr.read_r("./raw/train.rds")
  test_rds = pyreadr.read_r("./raw/test.rds")

# Create pandas data frames from files
train_df = pd.DataFrame.from_dict(train_rds[None])
test_df = pd.DataFrame.from_dict(test_rds[None])

# Data description

Describe the data and use a visualization to support your story. (approx. one or two paragraphs)

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316 entries, 0 to 315
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      316 non-null    category
 1   sex         316 non-null    category
 2   age         316 non-null    float64
 3   address     316 non-null    category
 4   famsize     316 non-null    category
 5   Pstatus     316 non-null    category
 6   Medu        316 non-null    float64
 7   Fedu        316 non-null    float64
 8   Mjob        316 non-null    category
 9   Fjob        316 non-null    category
 10  reason      316 non-null    category
 11  guardian    316 non-null    category
 12  traveltime  316 non-null    float64
 13  studytime   316 non-null    float64
 14  failures    316 non-null    float64
 15  schoolsup   316 non-null    category
 16  famsup      316 non-null    category
 17  paid        316 non-null    category
 18  activities  316 non-null    category
 19  nursery     316 non-null    category
 20  higher      316 non-null    category
 21  internet    316 non-null    category
 22  romantic    316 non-null    category
 23  famrel      316 non-null    float64
 24  freetime    316 non-null    float64
 25  goout       316 non-null    float64
 26  Dalc        316 non-null    float64
 27  Walc        316 non-null    float64
 28  health      316 non-null    float64
 29  absences    316 non-null    float64
 30  score       316 non-null    float64
dtypes: category(17), float64(14)
memory usage: 42.3 KB

In [ ]:
train_df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,score
0,GP,F,18.0,U,GT3,T,3.0,2.0,other,services,...,yes,yes,5.0,4.0,3.0,2.0,3.0,1.0,7.0,0.648402
1,GP,F,17.0,U,GT3,T,3.0,4.0,services,other,...,yes,no,4.0,4.0,5.0,1.0,3.0,5.0,16.0,1.169019
2,GP,M,17.0,U,GT3,T,2.0,3.0,other,other,...,yes,no,5.0,2.0,2.0,1.0,1.0,2.0,4.0,0.384039
3,GP,M,18.0,R,GT3,T,4.0,3.0,teacher,services,...,yes,yes,5.0,3.0,2.0,1.0,2.0,4.0,9.0,1.207493
4,GP,F,16.0,U,GT3,T,1.0,3.0,at_home,services,...,yes,yes,4.0,3.0,5.0,1.0,1.0,3.0,0.0,-1.215206

Warning: Total number of columns (31) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
train_df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,score
count,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000,316.000000
mean,16.753165,2.737342,2.503165,1.452532,2.034810,0.370253,3.933544,3.218354,3.066456,1.468354,2.287975,3.465190,5.718354,-0.016197
std,1.302923,1.105828,1.102662,0.690728,0.840667,0.788167,0.904318,0.972533,1.097767,0.881347,1.278385,1.385431,8.303744,0.986209
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-2.705322
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,-0.634936
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,3.500000,4.000000,-0.027688
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,0.640293
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,2.234578

In [ ]:
for col in train_df.select_dtypes(include=['object', 'category']).columns:
  print(f"{col}: {train_df[col].unique().tolist()}")

school: ['GP', 'MS']
sex: ['F', 'M']
address: ['U', 'R']
famsize: ['GT3', 'LE3']
Pstatus: ['T', 'A']
Mjob: ['other', 'services', 'teacher', 'at_home', 'health']
Fjob: ['services', 'other', 'at_home', 'teacher', 'health']
reason: ['other', 'course', 'home', 'reputation']
guardian: ['mother', 'father', 'other']
schoolsup: ['no', 'yes']
famsup: ['no', 'yes']
paid: ['no', 'yes']
activities: ['no', 'yes']
nursery: ['yes', 'no']
higher: ['yes', 'no']
internet: ['yes', 'no']
romantic: ['yes', 'no']

# Model description

Briefly describe which models you compare to perform prediction. (approx. two or three paragraphs)

K-NN
Random Forrest
XG-Boost
Log odds

# Data transformation and pre-processing

Describe additional pre-processing steps you have used, if any (e.g., dealing with categorical data, scaling). If you do not do any pre-processing, you can leave this section out.

In [ ]:
y = train_df['score']
X = train_df.drop(columns=['score'])

# convert category or object values into dummies
X_dummy = pd.get_dummies(X, drop_first=True)

# Model comparison

Describe how you compare the methods and why. (approx. two or three paragraphs)

In [ ]:
xbg_model = xgb.XGBRegressor(
    objective='reg:squarederror'
)

param_distributions = {
    'max_depth': randint(2, 30),                   # Integers: 2, 3, 4, 5
    'n_estimators': randint(50, 250),             # Integers: 50 to 249
    'learning_rate': loguniform(0.01, 0.2),       # Log-scaled floats
    'subsample': uniform(0.6, 0.35),              # Uniform floats: [0.60, 0.95]
    'colsample_bytree': uniform(0.6, 0.35),       # Uniform floats: [0.60, 0.95]
    'reg_alpha': loguniform(1e-3, 5.0),           # Log-scaled float
    'reg_lambda': loguniform(1e-2, 10.0)          # Log-scaled float
}

search = RandomizedSearchCV(
    estimator=xbg_model,
    param_distributions=param_distributions,
    n_iter=500, # How many combinations
    scoring='neg_root_mean_squared_error',
    cv=KFold(n_splits=5, shuffle=True), # Cross validation
    n_jobs=-1 # Run parallel using all processors.
)

search.fit(X, y)

print(f"Best CV RMSE: {-search.best_score_:.4f}")
print(f"Best Parameters: {search.best_params_}")

Best CV RMSE: 0.8626
Best Parameters: {'colsample_bytree': np.float64(0.9139966990970666), 'learning_rate': np.float64(0.03507455893172157), 'max_depth': 3, 'n_estimators': 76, 'reg_alpha': np.float64(0.06995999352186495), 'reg_lambda': np.float64(0.03279027091922544), 'subsample': np.float64(0.7017378518166948)}

In [ ]:
def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 4, 10),
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0)
    }

    xgb_model = xgb.XGBRegressor(
        objective= 'reg:squarederror',
        n_jobs= -1,
        **params
    )

    # Evaluate across folds using Negative Root Mean Squared Error
    scores = cross_val_score(
        xgb_model, X, y,
        cv=KFold(n_splits=5, shuffle=True, random_state=42),
        scoring='neg_root_mean_squared_error',
        n_jobs=-1
    )

    # Return average CV RMSE (Optuna minimizes this value)
    return np.mean(-scores)

# 3. Create Study & Optimize
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=500, show_progress_bar=True)

# 4. Output Results
print(f"Best CV RMSE: {study.best_value:.4f}")
print("Best Hyperparameters:")
for key, value in study.best_params.items():
    print(f"  {key}={value},")

[I 2026-09-24 09:25:01,756] A new study created in memory with name: no-name-c5d5b5be-92dd-4dd7-ba1a-6724dddeafd7

  0%|          | 0/500 [00:00<?, ?it/s]

[I 2026-09-24 09:25:04,542] Trial 0 finished with value: 0.8864474879822668 and parameters: {'max_depth': 5, 'n_estimators': 167, 'learning_rate': 0.032464748670697874, 'reg_alpha': 8.448592705784595, 'reg_lambda': 0.005731460348820518, 'subsample': 0.939789121552483, 'colsample_bytree': 0.6630522068820542}. Best is trial 0 with value: 0.8864474879822668.
[I 2026-09-24 09:25:05,327] Trial 1 finished with value: 0.8988690066087306 and parameters: {'max_depth': 8, 'n_estimators': 188, 'learning_rate': 0.0055462940190176115, 'reg_alpha': 0.0022412683196441404, 'reg_lambda': 1.315861625955499, 'subsample': 0.7769822212209396, 'colsample_bytree': 0.7317668812466491}. Best is trial 0 with value: 0.8864474879822668.
[I 2026-09-24 09:25:05,571] Trial 2 finished with value: 0.8838915502475784 and parameters: {'max_depth': 7, 'n_estimators': 56, 'learning_rate': 0.024566305007575305, 'reg_alpha': 0.22166135028347686, 'reg_lambda': 0.01616446239996158, 'subsample': 0.5197274330947861, 'colsample_bytree': 0.7502276956084559}. Best is trial 2 with value: 0.8838915502475784.
[I 2026-09-24 09:25:06,015] Trial 3 finished with value: 0.9481505361086162 and parameters: {'max_depth': 10, 'n_estimators': 252, 'learning_rate': 0.24421866175034274, 'reg_alpha': 0.276105655127175, 'reg_lambda': 0.0015637673254677693, 'subsample': 0.8517855689991995, 'colsample_bytree': 0.7790504655033408}. Best is trial 2 with value: 0.8838915502475784.
[I 2026-09-24 09:25:06,414] Trial 4 finished with value: 0.9550780621940929 and parameters: {'max_depth': 9, 'n_estimators': 228, 'learning_rate': 0.2611532238691076, 'reg_alpha': 0.00180254359105756, 'reg_lambda': 0.5178888612836984, 'subsample': 0.8180631127944935, 'colsample_bytree': 0.7959808237885031}. Best is trial 2 with value: 0.8838915502475784.
[I 2026-09-24 09:25:07,799] Trial 5 finished with value: 0.8884758267717029 and parameters: {'max_depth': 10, 'n_estimators': 410, 'learning_rate': 0.006352661696126369, 'reg_alpha': 0.35452289444233753, 'reg_lambda': 0.29554937035015816, 'subsample': 0.9326727878638668, 'colsample_bytree': 0.5544491781458291}. Best is trial 2 with value: 0.8838915502475784.
[I 2026-09-24 09:25:08,367] Trial 6 finished with value: 0.8865606237353871 and parameters: {'max_depth': 5, 'n_estimators': 290, 'learning_rate': 0.008399121709670793, 'reg_alpha': 0.03420539437482552, 'reg_lambda': 3.9327485138937406, 'subsample': 0.9347067439698356, 'colsample_bytree': 0.8540038635467808}. Best is trial 2 with value: 0.8838915502475784.
[I 2026-09-24 09:25:09,831] Trial 7 finished with value: 0.8967892008723556 and parameters: {'max_depth': 9, 'n_estimators': 481, 'learning_rate': 0.02311729458891889, 'reg_alpha': 0.10005658012231183, 'reg_lambda': 0.0007675544112204338, 'subsample': 0.7853640837861825, 'colsample_bytree': 0.8599871240655005}. Best is trial 2 with value: 0.8838915502475784.
[I 2026-09-24 09:25:10,577] Trial 8 finished with value: 0.8909131249992402 and parameters: {'max_depth': 10, 'n_estimators': 349, 'learning_rate': 0.09727836196449927, 'reg_alpha': 0.0015574352140240474, 'reg_lambda': 0.4698784048724535, 'subsample': 0.6884229775553923, 'colsample_bytree': 0.555370225634343}. Best is trial 2 with value: 0.8838915502475784.
[I 2026-09-24 09:25:11,205] Trial 9 finished with value: 0.8712155062457615 and parameters: {'max_depth': 4, 'n_estimators': 484, 'learning_rate': 0.005266600290650281, 'reg_alpha': 0.29839270715684274, 'reg_lambda': 1.1751047228235747, 'subsample': 0.6552685772553104, 'colsample_bytree': 0.6041846810832951}. Best is trial 9 with value: 0.8712155062457615.
[I 2026-09-24 09:25:12,669] Trial 10 finished with value: 0.8752637988890113 and parameters: {'max_depth': 9, 'n_estimators': 446, 'learning_rate': 0.005332846401164861, 'reg_alpha': 0.0215739269953684, 'reg_lambda': 1.5822304772948363, 'subsample': 0.6256288783156494, 'colsample_bytree': 0.867808461583872}. Best is trial 9 with value: 0.8712155062457615.
[I 2026-09-24 09:25:14,036] Trial 11 finished with value: 0.8796500190444508 and parameters: {'max_depth': 8, 'n_estimators': 460, 'learning_rate': 0.008658473516311785, 'reg_alpha': 0.01558290307444237, 'reg_lambda': 3.2716377815110995, 'subsample': 0.7031901466255674, 'colsample_bytree': 0.8551579354774}. Best is trial 9 with value: 0.8712155062457615.
[I 2026-09-24 09:25:14,724] Trial 12 finished with value: 0.87921013023775 and parameters: {'max_depth': 5, 'n_estimators': 441, 'learning_rate': 0.008710118672857108, 'reg_alpha': 0.016890302799735826, 'reg_lambda': 1.1315986180939968, 'subsample': 0.6539508974850462, 'colsample_bytree': 0.5260870357435906}. Best is trial 9 with value: 0.8712155062457615.
[I 2026-09-24 09:25:15,469] Trial 13 finished with value: 0.8652205334067625 and parameters: {'max_depth': 4, 'n_estimators': 433, 'learning_rate': 0.005012007831814986, 'reg_alpha': 0.007580288773381424, 'reg_lambda': 1.484574010871393, 'subsample': 0.5492924470715682, 'colsample_bytree': 0.9440819950404425}. Best is trial 13 with value: 0.8652205334067625.
[I 2026-09-24 09:25:16,325] Trial 14 finished with value: 0.8820795986458198 and parameters: {'max_depth': 4, 'n_estimators': 390, 'learning_rate': 0.015190209887957969, 'reg_alpha': 0.270687965788383, 'reg_lambda': 0.0972985900911933, 'subsample': 0.6779691176605854, 'colsample_bytree': 0.6151913088998369}. Best is trial 13 with value: 0.8652205334067625.
[I 2026-09-24 09:25:17,129] Trial 15 finished with value: 0.8668865644930221 and parameters: {'max_depth': 4, 'n_estimators': 390, 'learning_rate': 0.006004754459035163, 'reg_alpha': 0.013295023499703696, 'reg_lambda': 0.9438673389885235, 'subsample': 0.5455734619042121, 'colsample_bytree': 0.7737442698296396}. Best is trial 13 with value: 0.8652205334067625.
[I 2026-09-24 09:25:17,680] Trial 16 finished with value: 0.866271074223091 and parameters: {'max_depth': 4, 'n_estimators': 335, 'learning_rate': 0.00605861965807641, 'reg_alpha': 0.08198813737345724, 'reg_lambda': 0.38408633954641086, 'subsample': 0.6516598448694239, 'colsample_bytree': 0.9550746894513782}. Best is trial 13 with value: 0.8652205334067625.
[I 2026-09-24 09:25:18,186] Trial 17 finished with value: 0.8648221911109191 and parameters: {'max_depth': 4, 'n_estimators': 339, 'learning_rate': 0.006175005281729637, 'reg_alpha': 0.01205878169120461, 'reg_lambda': 0.13173091797820732, 'subsample': 0.5730102189096891, 'colsample_bytree': 0.9499133526391332}. Best is trial 17 with value: 0.8648221911109191.
[I 2026-09-24 09:25:18,658] Trial 18 finished with value: 0.8768364672864746 and parameters: {'max_depth': 4, 'n_estimators': 318, 'learning_rate': 0.01735004111124186, 'reg_alpha': 0.0023083171455852655, 'reg_lambda': 1.5109303397403002, 'subsample': 0.5145442321711959, 'colsample_bytree': 0.900061270651487}. Best is trial 17 with value: 0.8648221911109191.
[I 2026-09-24 09:25:19,214] Trial 19 finished with value: 0.8624710327185732 and parameters: {'max_depth': 4, 'n_estimators': 424, 'learning_rate': 0.005990719564940201, 'reg_alpha': 0.010970309091498149, 'reg_lambda': 0.9469853364723996, 'subsample': 0.5202904800294921, 'colsample_bytree': 0.9175055456507646}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:20,027] Trial 20 finished with value: 0.872217158445244 and parameters: {'max_depth': 5, 'n_estimators': 478, 'learning_rate': 0.008395108215960305, 'reg_alpha': 0.004270510861285105, 'reg_lambda': 0.2223894007876829, 'subsample': 0.5320615139547398, 'colsample_bytree': 0.8722690740447026}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:20,594] Trial 21 finished with value: 0.8681291597956114 and parameters: {'max_depth': 4, 'n_estimators': 414, 'learning_rate': 0.0051601993459614685, 'reg_alpha': 0.4188795491730418, 'reg_lambda': 0.8484889037100917, 'subsample': 0.5602107644551328, 'colsample_bytree': 0.9344230527318975}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:21,056] Trial 22 finished with value: 0.8803734806913441 and parameters: {'max_depth': 4, 'n_estimators': 314, 'learning_rate': 0.005852651253268548, 'reg_alpha': 0.03053275633532984, 'reg_lambda': 6.254884351774023, 'subsample': 0.6503516229899572, 'colsample_bytree': 0.8970169915752058}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:21,839] Trial 23 finished with value: 0.8994121928875785 and parameters: {'max_depth': 5, 'n_estimators': 461, 'learning_rate': 0.01790905643697603, 'reg_alpha': 0.01300545680081096, 'reg_lambda': 0.14406264439234648, 'subsample': 0.5939942357789617, 'colsample_bytree': 0.9805284643603425}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:22,352] Trial 24 finished with value: 0.8671475171903179 and parameters: {'max_depth': 4, 'n_estimators': 355, 'learning_rate': 0.005538049507461441, 'reg_alpha': 0.014244889845777283, 'reg_lambda': 0.014987091079501039, 'subsample': 0.5631330507236963, 'colsample_bytree': 0.8884744678265961}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:23,050] Trial 25 finished with value: 0.8658059670001335 and parameters: {'max_depth': 6, 'n_estimators': 321, 'learning_rate': 0.006624286283717407, 'reg_alpha': 0.030842049805783204, 'reg_lambda': 0.4013837470070669, 'subsample': 0.5388001965872463, 'colsample_bytree': 0.9412322568680692}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:23,546] Trial 26 finished with value: 0.868519782649725 and parameters: {'max_depth': 4, 'n_estimators': 366, 'learning_rate': 0.009134391849242085, 'reg_alpha': 0.0007937301566968402, 'reg_lambda': 0.4977526847338651, 'subsample': 0.5079520870663891, 'colsample_bytree': 0.836447730877347}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:24,273] Trial 27 finished with value: 0.8788804947584138 and parameters: {'max_depth': 5, 'n_estimators': 433, 'learning_rate': 0.005163691037040387, 'reg_alpha': 0.03421693354085103, 'reg_lambda': 6.557888076594479, 'subsample': 0.6357866129495469, 'colsample_bytree': 0.9347867983002928}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:24,893] Trial 28 finished with value: 0.8732832818911092 and parameters: {'max_depth': 5, 'n_estimators': 360, 'learning_rate': 0.01019337948358328, 'reg_alpha': 0.005664533160483567, 'reg_lambda': 1.083525301150433, 'subsample': 0.5272304833968295, 'colsample_bytree': 0.9840475858267159}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:25,499] Trial 29 finished with value: 0.8702836327093941 and parameters: {'max_depth': 4, 'n_estimators': 476, 'learning_rate': 0.009814292936914517, 'reg_alpha': 0.00114263184644073, 'reg_lambda': 2.7735429047853186, 'subsample': 0.5788169927156372, 'colsample_bytree': 0.8764533132452712}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:26,239] Trial 30 finished with value: 0.8688184075353254 and parameters: {'max_depth': 5, 'n_estimators': 437, 'learning_rate': 0.005636716722427028, 'reg_alpha': 0.08533482307392645, 'reg_lambda': 0.03458089318535763, 'subsample': 0.5023996010796202, 'colsample_bytree': 0.8980618098770348}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:26,767] Trial 31 finished with value: 0.8768297911370396 and parameters: {'max_depth': 4, 'n_estimators': 371, 'learning_rate': 0.011795556072275065, 'reg_alpha': 0.021691708246418216, 'reg_lambda': 0.10782229855128345, 'subsample': 0.5881598150583981, 'colsample_bytree': 0.9935460442319667}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:27,417] Trial 32 finished with value: 0.8820420741749342 and parameters: {'max_depth': 5, 'n_estimators': 362, 'learning_rate': 0.005372205773376547, 'reg_alpha': 0.03507908998703491, 'reg_lambda': 6.714164979748439, 'subsample': 0.5165927149880419, 'colsample_bytree': 0.8999824735487498}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:28,246] Trial 33 finished with value: 0.8625988701018426 and parameters: {'max_depth': 4, 'n_estimators': 425, 'learning_rate': 0.008692251997069966, 'reg_alpha': 0.017082203382174192, 'reg_lambda': 3.6919902293525775, 'subsample': 0.5245032413549088, 'colsample_bytree': 0.9962630760089869}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:29,128] Trial 34 finished with value: 0.8648491603518517 and parameters: {'max_depth': 4, 'n_estimators': 443, 'learning_rate': 0.009636446119559232, 'reg_alpha': 0.004316399460013814, 'reg_lambda': 5.356139292277878, 'subsample': 0.5305291312420335, 'colsample_bytree': 0.9880498458018161}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:30,085] Trial 35 finished with value: 0.8732999066515408 and parameters: {'max_depth': 4, 'n_estimators': 490, 'learning_rate': 0.00997905297914373, 'reg_alpha': 0.000813384213406042, 'reg_lambda': 3.6690536010023322, 'subsample': 0.5708632882826304, 'colsample_bytree': 0.9810969034690482}. Best is trial 19 with value: 0.8624710327185732.
[I 2026-09-24 09:25:30,895] Trial 36 finished with value: 0.8601334058078445 and parameters: {'max_depth': 4, 'n_estimators': 496, 'learning_rate': 0.0070577535920665095, 'reg_alpha': 0.005805601134360449, 'reg_lambda': 1.833026950566464, 'subsample': 0.509731120599099, 'colsample_bytree': 0.9927205292826262}. Best is trial 36 with value: 0.8601334058078445.
[I 2026-09-24 09:25:31,610] Trial 37 finished with value: 0.8818178291875007 and parameters: {'max_depth': 5, 'n_estimators': 404, 'learning_rate': 0.011727134393679126, 'reg_alpha': 0.013323273916910041, 'reg_lambda': 2.5857907148399066, 'subsample': 0.5644650597166898, 'colsample_bytree': 0.9418103911598508}. Best is trial 36 with value: 0.8601334058078445.
[I 2026-09-24 09:25:32,259] Trial 38 finished with value: 0.8686133090338594 and parameters: {'max_depth': 4, 'n_estimators': 478, 'learning_rate': 0.009378443357211231, 'reg_alpha': 0.006473919828783885, 'reg_lambda': 3.0622687637825865, 'subsample': 0.582959032224208, 'colsample_bytree': 0.9464204631739002}. Best is trial 36 with value: 0.8601334058078445.
[I 2026-09-24 09:25:32,956] Trial 39 finished with value: 0.8713295427684576 and parameters: {'max_depth': 5, 'n_estimators': 410, 'learning_rate': 0.009662309846965492, 'reg_alpha': 0.05910545211091167, 'reg_lambda': 2.4524978648471696, 'subsample': 0.5151168743215973, 'colsample_bytree': 0.9702001804850244}. Best is trial 36 with value: 0.8601334058078445.
[I 2026-09-24 09:25:33,622] Trial 40 finished with value: 0.8637502092865527 and parameters: {'max_depth': 4, 'n_estimators': 493, 'learning_rate': 0.0053146806888519, 'reg_alpha': 0.03025542931016751, 'reg_lambda': 2.6447617000253585, 'subsample': 0.5298670785067774, 'colsample_bytree': 0.985183216212746}. Best is trial 36 with value: 0.8601334058078445.
[I 2026-09-24 09:25:34,220] Trial 41 finished with value: 0.8685996138065082 and parameters: {'max_depth': 4, 'n_estimators': 430, 'learning_rate': 0.015120726336231538, 'reg_alpha': 0.030275108871670484, 'reg_lambda': 9.252648459482888, 'subsample': 0.5156972983616682, 'colsample_bytree': 0.9462662979255311}. Best is trial 36 with value: 0.8601334058078445.
[I 2026-09-24 09:25:34,967] Trial 42 finished with value: 0.8585528734326082 and parameters: {'max_depth': 4, 'n_estimators': 479, 'learning_rate': 0.00593580952070199, 'reg_alpha': 0.01571658115049497, 'reg_lambda': 1.5596601371116339, 'subsample': 0.5033059832047836, 'colsample_bytree': 0.9755447425008481}. Best is trial 42 with value: 0.8585528734326082.
[I 2026-09-24 09:25:35,803] Trial 43 finished with value: 0.8689657565498626 and parameters: {'max_depth': 5, 'n_estimators': 480, 'learning_rate': 0.0058453974629016645, 'reg_alpha': 0.005908126779472703, 'reg_lambda': 4.464194237918073, 'subsample': 0.5123722285852673, 'colsample_bytree': 0.9912162648814055}. Best is trial 42 with value: 0.8585528734326082.
[I 2026-09-24 09:25:36,464] Trial 44 finished with value: 0.8610142815182964 and parameters: {'max_depth': 4, 'n_estimators': 473, 'learning_rate': 0.008350380405248957, 'reg_alpha': 0.014987349205823937, 'reg_lambda': 1.560929713299437, 'subsample': 0.5040186563098333, 'colsample_bytree': 0.966777561676264}. Best is trial 42 with value: 0.8585528734326082.
[I 2026-09-24 09:25:37,073] Trial 45 finished with value: 0.8721432383695795 and parameters: {'max_depth': 4, 'n_estimators': 486, 'learning_rate': 0.009603482246564704, 'reg_alpha': 0.0184561154576199, 'reg_lambda': 0.4471177908248541, 'subsample': 0.5007820285987189, 'colsample_bytree': 0.9385015367138023}. Best is trial 42 with value: 0.8585528734326082.
[I 2026-09-24 09:25:37,736] Trial 46 finished with value: 0.8679865078407353 and parameters: {'max_depth': 4, 'n_estimators': 499, 'learning_rate': 0.007937179378308385, 'reg_alpha': 0.004776169235115595, 'reg_lambda': 0.9904156858653451, 'subsample': 0.5223157595576366, 'colsample_bytree': 0.9441742305221222}. Best is trial 42 with value: 0.8585528734326082.
[I 2026-09-24 09:25:38,420] Trial 47 finished with value: 0.8793143467870165 and parameters: {'max_depth': 4, 'n_estimators': 491, 'learning_rate': 0.010629573310288375, 'reg_alpha': 0.01686134341036429, 'reg_lambda': 1.0616187360216618, 'subsample': 0.6084442394094827, 'colsample_bytree': 0.9808814874200511}. Best is trial 42 with value: 0.8585528734326082.
[I 2026-09-24 09:25:39,343] Trial 48 finished with value: 0.858296888311612 and parameters: {'max_depth': 4, 'n_estimators': 490, 'learning_rate': 0.006049464684854325, 'reg_alpha': 0.029873552485641885, 'reg_lambda': 0.20047779310324987, 'subsample': 0.5193927114300233, 'colsample_bytree': 0.9723684403678811}. Best is trial 48 with value: 0.858296888311612.
[I 2026-09-24 09:25:40,782] Trial 49 finished with value: 0.8862691845761846 and parameters: {'max_depth': 4, 'n_estimators': 459, 'learning_rate': 0.014526706105091384, 'reg_alpha': 0.059580950307050004, 'reg_lambda': 1.596217941934328, 'subsample': 0.5129262106663781, 'colsample_bytree': 0.9670230882552362}. Best is trial 48 with value: 0.858296888311612.
[I 2026-09-24 09:25:41,781] Trial 50 finished with value: 0.8836278300916678 and parameters: {'max_depth': 4, 'n_estimators': 472, 'learning_rate': 0.012696549239242771, 'reg_alpha': 0.01323408656367817, 'reg_lambda': 0.1059403249143151, 'subsample': 0.5033539411591277, 'colsample_bytree': 0.9609720170635621}. Best is trial 48 with value: 0.858296888311612.
[I 2026-09-24 09:25:42,408] Trial 51 finished with value: 0.8663379726523555 and parameters: {'max_depth': 4, 'n_estimators': 418, 'learning_rate': 0.006422113544598813, 'reg_alpha': 0.010571023685362701, 'reg_lambda': 5.94243019292466, 'subsample': 0.5013458476534081, 'colsample_bytree': 0.9935946160541139}. Best is trial 48 with value: 0.858296888311612.
[I 2026-09-24 09:25:43,096] Trial 52 finished with value: 0.8582643800685791 and parameters: {'max_depth': 4, 'n_estimators': 480, 'learning_rate': 0.006429934602554558, 'reg_alpha': 0.02780320312894853, 'reg_lambda': 1.5206286013618364, 'subsample': 0.5065206996588649, 'colsample_bytree': 0.9166298496472359}. Best is trial 52 with value: 0.8582643800685791.
[I 2026-09-24 09:25:43,750] Trial 53 finished with value: 0.8669074170394158 and parameters: {'max_depth': 4, 'n_estimators': 475, 'learning_rate': 0.0082544298229614, 'reg_alpha': 0.0019612303490247505, 'reg_lambda': 0.6872389595821162, 'subsample': 0.5594386976260387, 'colsample_bytree': 0.99086097398589}. Best is trial 52 with value: 0.8582643800685791.
[I 2026-09-24 09:25:44,491] Trial 54 finished with value: 0.8655088461669853 and parameters: {'max_depth': 5, 'n_estimators': 450, 'learning_rate': 0.007414307353705824, 'reg_alpha': 0.019454463675906076, 'reg_lambda': 1.6963353707687292, 'subsample': 0.5196066869698228, 'colsample_bytree': 0.9156781529046498}. Best is trial 52 with value: 0.8582643800685791.

Random Forest Regression

In [ ]:
# fit the estimator
rf_model = RandomForestRegressor(random_state = 42)
rf_model.fit(X_dummy, y)

# 5-fold cross-validation before hyperparameter tuning
rf_cross_val_scores = cross_val_score(
    rf_model,
    X_dummy,
    y,
    cv=5,
    scoring="neg_mean_squared_error"
)

rf_MSE = -(rf_cross_val_scores)
print(rf_MSE)

[0.81738261 0.64921965 0.74710535 0.86050946 0.86272463]

In [ ]:
# hyperparameter tuning
# check current parameters
rf_model.get_params()

param_distributions = {
    'n_estimators': list(range(50, 301, 50)),   # number of trees
    'max_features': ['sqrt', 'log2', 1.0],      # max number of features considered for splitting a node
    'max_depth': [None, 3, 5, 10, 15],          # max number of levels in each tree
    'min_samples_split': [2, 5, 10],            # min number of data points placed in a node before the node is split
    'min_samples_leaf': [1, 2, 4],              # min number of data points allowed in a leaf node
    'bootstrap': [True, False]                  # sampling data points with or without replacement
}

rf_search = RandomizedSearchCV(
    estimator = rf_model,
    param_distributions = param_distributions,
    n_iter = 100,
    cv = 5,
    scoring="neg_mean_squared_error",
    n_jobs = -1
)

rf_search.fit(X_dummy, y)
rf_search.best_params_

{'n_estimators': 150,
 'min_samples_split': 10,
 'min_samples_leaf': 4,
 'max_features': 1.0,
 'max_depth': 5,
 'bootstrap': True}

In [ ]:
# fit model again with the new hyperparameters
rf_model_best_params = RandomForestRegressor (random_state = 42,
                                              n_estimators = 150,
                                              min_samples_split =10,
                                              min_samples_leaf = 4,
                                              max_features = 1.0,
                                              max_depth = 5,
                                              bootstrap = True)

# 5-fold cross-validation after hyperparameter tuning
rf_cross_val_scores_best_params = cross_val_score(
    rf_model_best_params,
    X_dummy,
    y,
    cv=5,
    scoring="neg_mean_squared_error"
)

rf_MSE_best_params = -(rf_cross_val_scores_best_params)
print(rf_MSE_best_params) # MSE scores seem to be a bit lower

[0.7797422  0.66489943 0.70728408 0.7609683  0.81044186]

# Chosen model

Show which method is best and why. (approx. one paragraph) You are welcome to use tables and plots!

[link text](https://)

# Team member contributions

Write down what each team member contributed to the project.

- Author One: a, b, c
- Author Two: b, c, d
- Author Three: a, b, d